### PR TITLE
Fixed error caused by middleware.

### PR DESCRIPTION
**Pull request by Dynamic-Gravity**
Incorretly linked the body-Parser package when the actual npm module is body-parser.

converted to ES6

### CODE REVIEW

**Comment by Dynamic-Gravity** [comment]
> @Dynamic-Gravity Ok it now works on windows machine (tried on Mac last night it didn't work) but in console it now says cannot read name of undefined so the problem is in the React code. If I try to not bind the handleSubmit method I get `cannot read property 'refs' of undefined.

I'm not sure how you were able to get to this step, because on a fresh clone, after installing the deps, run the `node index` to fire up the server and it crashes instantly. Since `body-parser` is what crashed, this takes out your ability to parse incoming requests.

**Comment by pinglinh** [comment]
@Dynamic-Gravity do you not get an error in the chrome console saying 
`Uncaught (in promise) TypeError: Cannot read property 'name' of undefined` 

This is when I input lat: 25 and lng: -80 on the front end

**Comment by Dynamic-Gravity** [comment]
Nope, I get a success. Nothing is returned though, because I don't have the same data as you in my mongodb.

Could you give me a sample data of what you should expect, and then I will test again. At this time, I see a proper hit on my api endpoint.

**Comment by pinglinh** [comment]
@Dynamic-Gravity how do you start the MongoDB ? Seems like I am getting different errors on Mac and Windows. On the Mac I can't even start up the database. Apparently `Data directory /data/db not found., terminating` 

Not sure where to create it on a Mac...

My data is the same as from the tutorial.

**Pull request merged**
